main_service: node
services:
  node:
    image: node:22.13.1-slim
test_commands:
  - "npx jest --coverage --coverageReporters=json --json --outputFile=jest-results.json --collectCoverageFrom='**/*.{js,jsx}' --coveragePathIgnorePatterns='node_modules' --passWithNoTests || [ $? -eq 1 -o $? -eq 5 ]"
  - "if [ -f 'coverage/coverage-final.json' ]; then mv coverage/coverage-final.json coverage.json; else echo 'Warn: coverage/coverage-final.json not found'; exit 1; fi"
single_file_test_commands:
  - "npx jest --coverage --coverageReporters=json --json --outputFile=jest-results.json --testPathPattern=$TEST_FILE --collectCoverageFrom=$TO_BE_COVERED_FILE --passWithNoTests || [ $? -eq 1 -o $? -eq 5 ]"
  - "if [ -f 'coverage/coverage-final.json' ]; then mv coverage/coverage-final.json coverage.json; else echo 'Warn: coverage/coverage-final.json not found'; exit 1; fi"
setup_commands:
  - npm install -g pnpm
  - pnpm install --silent
  - pnpm add --silent jest
  - pnpm add --silent jest-json-reporter
  - pnpm add -D --silent babel
  - pnpm add --silent @babel/core
  - pnpm add --silent @babel/preset-env
  - pnpm add --silent @babel/preset-react
  - pnpm add --silent @testing-library/react
  - pnpm add --silent @testing-library/jest-dom
  - pnpm add --silent @testing-library/user-event
  - pnpm add --silent jest-environment-jsdom
  - "[ -f babel.config.js ] || echo 'module.exports={presets:[[\"@babel/preset-env\",{targets:{node:\"current\"}}],\"@babel/preset-react\"]}' > babel.config.js"
  - "[ -f jest.config.js ] || echo 'module.exports={testEnvironment:\"jsdom\",transform:{\".+\\\\.(js|jsx)$\":\"babel-jest\"}}' > jest.config.js"
ignore:
  - "*prettierrc*"
  - "*eslintrc*"
  - "*stylelintrc*"
  - "*commitlintrc*"
  - "*lintstagedrc*"
  - "*huskyrc*"
  - "*config.test.*"
  - "*.config.js"
  - "*.config.jsx"
