main_service: node
services:
  node:
    image: node:22.13.1-slim
test_commands:
  - "npx jest --coverage --coverageReporters=json --json --outputFile=jest-results.json --collectCoverageFrom='**/*.{js,jsx,ts,tsx}' --coveragePathIgnorePatterns='node_modules' --passWithNoTests || [ $? -eq 1 -o $? -eq 5 ]"
  - "if [ -f 'coverage/coverage-final.json' ]; then mv coverage/coverage-final.json coverage.json; else echo 'Warn: coverage/coverage-final.json not found'; exit 1; fi"
single_file_test_commands:
  - "npx jest --coverage --coverageReporters=json --json --outputFile=jest-results.json --testPathPattern=$TEST_FILE --collectCoverageFrom=$TO_BE_COVERED_FILE --passWithNoTests || [ $? -eq 1 -o $? -eq 5 ]"
  - "if [ -f 'coverage/coverage-final.json' ]; then mv coverage/coverage-final.json coverage.json; else echo 'Warn: coverage/coverage-final.json not found'; exit 1; fi"
setup_commands:
  - yarn install --silent --legacy-peer-deps || true
  - yarn list jest >/dev/null 2>&1 || yarn add -D --silent jest
  - yarn list ts-jest >/dev/null 2>&1 || yarn add -D --silent ts-jest
  - yarn list typescript >/dev/null 2>&1 || yarn add -D --silent typescript
  - yarn list @types/jest >/dev/null 2>&1 || yarn add -D --silent @types/jest
  - yarn list ts-node >/dev/null 2>&1 || yarn add -D --silent ts-node
  - yarn list jest-json-reporter >/dev/null 2>&1 || yarn add -D --silent jest-json-reporter
  - yarn list @babel/core >/dev/null 2>&1 || yarn add -D --silent @babel/core
  - yarn list @babel/preset-typescript >/dev/null 2>&1 || yarn add -D --silent @babel/preset-typescript
  - yarn list @babel/preset-react >/dev/null 2>&1 || yarn add -D --silent @babel/preset-react
  - yarn list @babel/preset-env >/dev/null 2>&1 || yarn add -D --silent @babel/preset-env
  - yarn list @babel/preset-flow >/dev/null 2>&1 || yarn add -D --silent @babel/preset-flow
  - yarn list @babel/plugin-syntax-jsx >/dev/null 2>&1 || yarn add -D --silent @babel/plugin-syntax-jsx
  - yarn list @babel/plugin-syntax-flow >/dev/null 2>&1 || yarn add -D --silent @babel/plugin-syntax-flow
  - yarn list @testing-library/react >/dev/null 2>&1 || yarn add -D --silent @testing-library/react
  - yarn list @testing-library/jest-dom >/dev/null 2>&1 || yarn add -D --silent @testing-library/jest-dom
  - yarn list @testing-library/user-event >/dev/null 2>&1 || yarn add -D --silent @testing-library/user-event
  - yarn list jest-environment-jsdom >/dev/null 2>&1 || yarn add -D --silent jest-environment-jsdom
  - '[ -f tsconfig.json ] || echo ''{"compilerOptions":{"target":"es5","module":"commonjs","strict":true,"esModuleInterop":true,"skipLibCheck":true,"forceConsistentCasingInFileNames":true,"jsx":"react-jsx","types":["jest","node"]}}'' > tsconfig.json'
  - '[ -f babel.config.js ] || echo ''module.exports={presets:[["@babel/preset-env",{targets:{node:"current"}}],"@babel/preset-typescript","@babel/preset-react"]}'' > babel.config.js'
ignore:
  - "*prettierrc*"
  - "*eslintrc*"
  - "*stylelintrc*"
  - "*commitlintrc*"
  - "*lintstagedrc*"
  - "*huskyrc*"
  - "*config.test.*"
  - "*.config.js"
  - "*.config.ts"
  - "*.config.jsx"
